# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 42ad5fb1c8f645c2a0e8ca297ca9bc394cb85da67798c16334ad68f2c8d0021ce5747503ea174ded599afc5d560d7dc59ff12adf65ce9128fe701f6234e592f6

test:
  secret_key_base: 56b037ec3885845e59193d0d579da209e4d1dfd568e3142ab3c35968656dd07e5c71098781cc99fbfa9abcfcbb2415db49c1f1b8b391e6a9815eb8cf307d817a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
